### ISSUE TITLE
Implement Weisfeiller-Lehman hashes as pre-screening speed up matching

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/matbench-genmetrics#21]
https://github.com/sparks-baird/matbench-genmetrics/issues/9#issuecomment-1200115723

https://github.com/kjappelbaum/structure_comp/blob/e903be460f9ed609814240a8b2b7c1702e232a48/structure_comp/remove_duplicates.py#L453

https://github.com/kjappelbaum/structuregraph-helpers/blob/main/src/structuregraph_helpers/hash.py?rgh-link-date=2022-07-29T06%3A30%3A36Z

See:
https://github.com/sparks-baird/matbench-genmetrics/blob/b8283a87a7c0c18b65e21642161f1344b7058d98/src/matbench_genmetrics/core.py#L101-L112

I might make a separate function for pairwise distance matrices within a set vs. between two sets to lessen repeat work for the uniqueness metric.

The nested for loop could also probably stand to be replaced by `https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html`

**Comment by sgbaird** [comment]
@kjappelbaum are you OK with making a PR for this one?

**Comment by kjappelbaum** [comment]
yea, I just need to get something else done this WE first. Will try to get to it next week.

**Comment by kjappelbaum** [comment]
What is the status of this? From our last discussion I recall that you prefer going via the fingerprints, right?

**Comment by sgbaird** [comment]
@kjappelbaum thanks for following up, and sorry for not mentioning in this issue before. That's correct - for now I think it's best to go with fingerprints.

**Comment by kjappelbaum** [comment]
Shall we close this issue? I understand that there is no need for a PR for this anymore?
