### ISSUE TITLE
Consider use of fingerprint distance instead of `StructureMatcher` for comparison between generated and test

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/matbench-genmetrics#39]
From CDVAE paper:

> We use fingerprint distance, rather than RMSE from StructureMatcher (Ong et al., 2013), because the material space is too large for the models to generate enough materials to exactly match the ground truth materials. StructureMatcher first requires the compositions of two materials to exactly match, which will cause all models to have close-to-zero coverage.

**Comment by sgbaird** [comment]
https://github.com/sparks-baird/matbench-genmetrics/issues/38

**Comment by sgbaird** [comment]
Compare matminer featurizers with hash approach

**Comment by kjappelbaum** [comment]
Ok, how do we design the experiment?

Potential fingerprints: 
- PXRD pattern
- SOAP 
- JarvisCFID

Then, look at how the distribution of pairwise distances looks like. How many in 1% percentile distance, etc.?

**Comment by sgbaird** [comment]
Found this from [CDVAE manuscript](https://arxiv.org/abs/2206.12159) which is right in line with [what you mentioned previously](https://github.com/sparks-baird/matbench-genmetrics/issues/9#issue-1298536484):

> ![image](https://user-images.githubusercontent.com/45469701/182911238-96f31760-cb11-4ba9-9a92-558227b5f1a6.png)

> Figure 8: Change of COV-R and COV-P by varying δstruc: and δcomp: for MP-20. Dashed line
denotes the current chosen thresholds.

They used Euclidean distances between Magpie feature vectors for compositional distance and between CrystalNN fingerprint for structural fingerprints, and a "match" meant both the compositional and structural (Euclidean) distances were lower than (somewhat) arbitrarily chosen thresholds. I lean towards using ElMD for the compositional distance via [chem_wasserstein](https://github.com/sparks-baird/chem_wasserstein). Maybe using Earth Mover's Distance for the CrystalNN fingerprint as well via [dist-matrix](https://github.com/sparks-baird/dist-matrix). For now for simplicity, maybe stick with CDVAE's implementation?

**Comment by sgbaird** [comment]
`cdvae_coverage` as default now

**Comment by sgbaird** [comment]
Planning to implement loading precomputed compositional and structural fingerprints from FigShare (still need to calculate and upload) to save time computing the metric, since the structural fingerprinting can take a while. The fingerprints for generated structures will still need to be computed by the user, but should only be a few minutes for 1000 structures.

https://github.com/sparks-baird/mp-time-split/issues/42

**Comment by sgbaird** [comment]
Can always circle back to this or create a new issue, but a CDVAE-style implementation of a coverage metric seems to be functional now.
