### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/matbench-genmetrics#49]
https://github.com/conda-forge/staged-recipes/pull/19864

**Comment by kjappelbaum** [comment]
the wait time for review is quite long atm :D

**Comment by sgbaird** [comment]
It would appear so :D must be a lot of (tedious) work for the conda-forge devs to ingest new packages constantly

**Comment by sgbaird** [comment]
Available, and now just needs to get bumped to the most recent version (i.e. waiting on the conda-forge bot to create a PR). @kjappelbaum thanks for getting `element-coder` up on `conda-forge` and sorting out other dependency stuff.
