### ISSUE TITLE
integration of energy above hull predictor

### ISSUE THREAD

**Issue by sgbaird** [sparks-baird/matbench-genmetrics#55]
Preferably one trained on both relaxed and unrelaxed structures, and one with minimal dependency issues. CDVAE does something similar, but the dependencies/build are too fragile at the moment to integrate into `matbench-genmetrics`.

Related to this, I came across [an article](https://dx.doi.org/10.1016/j.jssc.2020.121557) saying effectively "don't discard structures just because they have a high energy above hull, e.g. over 200 meV/atom":

> (1) Pöhls, J.-H.; Heyberger, M.; Mar, A. Comparison of Computational and Experimental Inorganic Crystal Structures. Journal of Solid State Chemistry 2020, 290, 121557. https://doi.org/10.1016/j.jssc.2020.121557.

Some options:
- `m3gnet`
- `alignn`
- `wren`
- `schnetpack`
- `cgcnn`
- one of the submodels from CDVAE

Something that can be pip and/or conda installed, has state-of-the-art predictive performance, and can be called with just a few lines of code:
```python
from codebase import MyPretrainedModel
ehull_pred = MyPretrainedModel.predict(structures, property="e_above_hull")
```
in addition to the note above about being trained on both relaxed and unrelaxed structures. I think I could use the "MP + WBM" dataset mentioned by Rhys in https://github.com/materialsproject/matbench/issues/104#issuecomment-1030739336.

See also [Data-Augmentation for Graph Neural Network Learning of the Relaxed Energies of Unrelaxed Structures](https://arxiv.org/abs/2202.13947)

Other related repos:
- https://github.com/CJBartel/TestStabilityML
- https://github.com/kaist-amsg/Synthesizability-PU-CGCNN

**Comment by sgbaird** [comment]
There is also the question of whether this should be a separate implementation/repository and whether crystal generative benchmarks should depend on a property predictor.

**Comment by kjappelbaum** [comment]
I think this is a really tricky thing because you'll often be out of the domain on which these models have been trained on.

**Comment by sgbaird** [comment]
@kjappelbaum good point. Opens a whole new can of worms. Maybe we leave this out for now.
